import i18n from "./i18n";

/**
 * 图片多国语言替换
 * 注意:图片必须放在工程
 * resources/lang/
 * 目录下面,文件名字必须是
    _  下划线 + 
    zh_CN   : 'zh-CN',
    zh_HK   : 'zh-HK',
    en      : 'en',
    jo      : 'jo',
    ko      : 'ko'
    结尾
 */
const { ccclass, property } = cc._decorator;

@ccclass
export default class i18nSprite extends cc.Component {

    @property({
        displayName: '默认图片路径'
    })
    public spriteName: string = '';

    onLoad() {
        let sprite = this.node.getComponent(cc.Sprite);
        if (sprite) {
            cc.resources.load('lang/' + sprite.spriteFrame.name + '_' + i18n.lang(),
                cc.SpriteFrame,
                (err, sprintFrame: cc.SpriteFrame) => {
                    if (err) {
                        cc.error(err);
                    } else {
                        sprite.spriteFrame = sprintFrame;
                    }
                })
        }
    }

}
